# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Victoria Cao"
subtitle: "See the world through my eyes!"
author: "Victoria Cao"
header:
 title: "Photography"
 subtitle: "by Victoria Cao"
footer:
 name: "Hi there, I'm Victoria!"
 bio: "I'm a Senior at Michigan State University that takes photos :)"
 github: ""
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/toriacao"
  linkedin: "https://www.linkedin.com/in/caovicto/"
  github: "https://www.github.com/caovicto"
